services:
  - type: web
    name: tekel-pos
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class sync
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0